# Generated by Django 5.0.7 on 2024-07-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish_search',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('items', models.JSONField()),
                ('cordinates', models.CharField(max_length=50)),
                ('detailDump', models.JSONField()),
            ],
        ),
    ]
